server:
  port: 8080
  compression:
    enabled: true
    mime-types:
      - application/json
      - application/xml
      - text/html
      - text/plain
    min-response-size: 2KB
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway

  http:
    codecs:
      max-in-memory-size: 10MB

  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s
        wiretap: false
      default-filters:
        - 'RemoveRequestHeader=Cookie'
        - 'RemoveResponseHeader=Set-Cookie'
        - 'DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE'
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: timeclock-service
          uri: lb://timeclock-service
          predicates:
            - Path=/api/timeclock/**
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true

# Propiedades propias
security:
  public-paths:
    - /actuator/**
    - /auth/**
    - /public/**
    - /docs/**
    - /swagger-ui/**
    - /v3/api-docs/**
    - /favicon.ico
    - /

jwt:
  issuer: timelogic-gateway
  audience: timelogic-services
  # Debe ser IGUAL que en el gateway (modo HS256 dev)
  secret: 'q7Y0yP8o4bXy2o7q0kE2oH7kxb1KJm6l4pZ9wTqE4wk='
  # skew opcional si hay desfases de reloj
  allowed-skew-seconds: 60

cors:
  allowed-origins: 'http://localhost:4200,http://localhost:3000'
  allowed-methods: 'GET,POST,PUT,DELETE,OPTIONS'
  allowed-headers: '*'
  exposed-headers: 'X-User-Id,X-User-Email,X-User-Name,X-User-Roles'
  allow-credentials: true

auth:
  internal:
    enabled: true
    # Dev: HS256 (clave compartida). En prod, mejor RS256 con clave pública/privada.
    alg: HS256
    issuer: timelogic-gateway
    audience: timelogic-services
    ttl-seconds: 600
    # genera con:  openssl rand -base64 32
    secret: 'q7Y0yP8o4bXy2o7q0kE2oH7kxb1KJm6l4pZ9wTqE4wk='

headers:
  user-id: X-User-Id
  user-email: X-User-Email
  user-name: X-User-Name
  user-roles: X-User-Roles

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - env
          - metrics
          - threaddump
  endpoint:
    health:
      probes:
        enabled: true