spring:
  application:
    name: timeclock-service
  datasource:
    url: jdbc:postgresql://localhost:5434/timeclockdb
    username: timelogic
    password: timelogic
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
